### ISSUE TITLE
make migration files

### ISSUE THREAD

**Issue by kahirokunn** [k-okina/cp-api#1]

**Comment by takeokunn** [comment]
- [x] users
- [x] profiles
- [x] portfolios
- [x] communities
- [x] communities_users
- [x] community_messages
- [x] chatroom_messages
- [x] chatrooms_users
- [x] chatrooms

**Comment by kahirokunn** [comment]
I already made tables.
Please give me next work.
Thx.
![LGTM](https://lgtm.in/p/48J82RCPp)
